version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      #prod or dev
      target: dev
      context: .
    command: ["dev", "--port", $PORT]
    ports:
      - $PORT:$PORT
    volumes:
      - ./src/:/var/www/http/app/src
      - ./public/:/var/www/http/app/public
    environment:
      PORT: $PORT
      VITE_BACKEND_URL: $VITE_BACKEND_URL
      VITE_STATIC_URL: $VITE_STATIC_URL
