version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
    command: yarn dev --host
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    restart: always
