version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        NODE_ENV: development
    command: "dev"
    ports:
      - $PORT:$PORT
    volumes:
      - ./src/:/var/www/http/app/src
      - ./public/:/var/www/http/app/public
    environment:
      VITE_BACKEND_URL: $BACKEND_URL
      VITE_STATIC_URL: $STATIC_URL
