version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        NODE_ENV: development
    command: "dev --host"
    ports:
      - 5173:5173
    volumes:
      - ./src/:/var/www/http/app/src
      - ./public/:/var/www/http/app/public
    environment:
      VITE_BACKEND_URL: "http://127.0.0.1:3000"