<template>
  <nav
    class="
      relative
      w-full
      flex
      flex-wrap
      items-center
      justify-between
      py-1
      bg-accent
      text-gray-500
      hover:text-base-300
      focus:text-base-300
      shadow-lg"
  >
    <div
      class="
        container-fluid
        w-full
        flex
        flex-wrap
        items-center
        justify-between
        px-3"
    >
      <div
        class="
          flex
          items-center
          text-gray-900
          hover:text-gray-900
          focus:text-gray-900
          mr-1"
      >
        <!-- title -->
        <slot></slot>
      </div>
      <div class="
        flex
        items-center
        gap-1
        text-gray-900
        hover:text-accent
        hover:bg-gray-900
        focus:text-accent
        focus:bg-gray-900
        p-1
        px-3
        rounded
        cursor-pointer
      ">
        <font-awesome-icon icon="fa-circle-question" />
        How to play
      </div>
    </div>
  </nav>
</template>